/* eslint-disable */
const fs = require('fs')
const path = require('path')

// Read original file (which is corrupted) - we need to generate the corrected version
// Instead, create the corrected file from scratch

const original = [
  "import type { Knex } from 'knex';",
  "import Decimal from 'decimal.js';",
  "import type { ILedgerRepository } from '../../src/modules/ledger/ledger.repository.interface';",
  "import type { IWalletRepository } from '../../src/modules/wallet/wallet.repository.interface';",
  "import { WalletService } from '../../src/modules/wallet/wallet.service';",
  "import { InsufficientFundsException, BadRequestException } from '../../src/common/exceptions/http.exception';",
  "import { ErrorLogger } from '../../src/common/filters/error.middleware';",
  "import { LedgerEntryType, SortOrder, LogLevel, ErrorCode } from '../../src/common/enums';",
  '',
  'const mockTransaction = {',
  '  commit: jest.fn().mockResolvedValue(undefined),',
  '  rollback: jest.fn().mockResolvedValue(undefined),',
  '};',
  '',
  "jest.mock('../../config/database', () => ({",
  '  __esModule: true,',
  '  default: {',
  '    transaction: jest.fn((callback: (trx: unknown) => Promise<unknown>) => callback(mockTransaction)),',
  '  },',
  '}));',
  '',
  "jest.mock('../../src/common/filters/error.middleware', () => ({",
  '  ErrorLogger: {',
  '    log: jest.fn(),',
  '  },',
  '}));',
  '',
  'interface WalletSnapshot {',
  '  id: number;',
  '  user_id: number;',
  '  balance: string;',
  '  created_at: Date;',
  '  updated_at: Date;',
  '}',
  '',
  'interface LedgerSnapshot {',
  '  id: number;',
  '  wallet_id: number;',
  '  amount: string;',
  '  type: LedgerEntryType;',
  '  description: string;',
  '  created_at: Date;',
  '}',
  '',
  'interface MockTransaction {',
  '  commit: jest.Mock;',
  '  rollback: jest.Mock;',
  '}',
  '',
  'function createMockTransaction(): MockTransaction {',
  '  return {',
  '    commit: jest.fn().mockResolvedValue(undefined),',
  '    rollback: jest.fn().mockResolvedValue(undefined),',
  '  };',
  '}',
  '',
  'class InMemoryWalletRepository implements IWalletRepository {',
  '  private readonly wallets: Map<number, WalletSnapshot> = new Map();',
  '  private readonly userIdIndex: Map<number, number> = new Map();',
  '',
  '  constructor(initialData: WalletSnapshot[] = []) {',
  '    for (const wallet of initialData) {',
  '      this.wallets.set(wallet.id, { ...wallet });',
  '      this.userIdIndex.set(wallet.user_id, wallet.id);',
  '    }',
  '  }',
  '',
  '  public async findByUserIdForUpdate(userId: number, _trx: Knex.Transaction): Promise<WalletSnapshot | null> {',
  '    const walletId = this.userIdIndex.get(userId);',
  '    if (walletId === undefined) {',
  '      return null;',
  '    }',
  '    const wallet = this.wallets.get(walletId);',
  '    return wallet ? { ...wallet } : null;',
  '  }',
  '',
  '  public async findByUserId(userId: number, _trx: Knex.Transaction): Promise<WalletSnapshot | null> {',
  '    const walletId = this.userIdIndex.get(userId);',
  '    if (walletId === undefined) {',
  '      return null;',
  '    }',
  '    const wallet = this.wallets.get(walletId);',
  '    return wallet ? { ...wallet } : null;',
  '  }',
  '',
  '  public async findByWalletId(walletId: number, _trx: Knex.Transaction): Promise<WalletSnapshot | null> {',
  '    const wallet = this.wallets.get(walletId);',
  '    return wallet ? { ...wallet } : null;',
  '  }',
  '',
  '  public async updateBalance(walletId: number, amount: string, _trx: Knex.Transaction): Promise<void> {',
  '    const wallet = this.wallets.get(walletId);',
  '    if (!wallet) {',
  '      throw new Error(`Wallet ${walletId} not found`);',
  '    }',
  '    wallet.balance = amount;',
  '    wallet.updated_at = new Date();',
  '  }',
  '',
  '  public async createWallet(userId: number, _trx: Knex.Transaction): Promise<WalletSnapshot> {',
  '    const id = this.wallets.size + 1;',
  '    const now = new Date();',
  '    const wallet: WalletSnapshot = {',
  '      id,',
  '      user_id: userId,',
  "      balance: '0',",
  '      created_at: now,',
  '      updated_at: now,',
  '    };',
  '    this.wallets.set(id, wallet);',
  '    this.userIdIndex.set(userId, id);',
  '    return { ...wallet };',
  '  }',
  '',
  '  public async incrementBalance(walletId: number, amount: string, _trx: Knex.Transaction): Promise<void> {',
  '    const wallet = this.wallets.get(walletId);',
  '    if (!wallet) {',
  '      throw new Error(`Wallet ${walletId} not found`);',
  '    }',
  '    const current = new Decimal(wallet.balance);',
  '    const add = new Decimal(amount);',
  '    wallet.balance = current.plus(add).toFixed(0);',
  '    wallet.updated_at = new Date();',
  '  }',
  '',
  '  public async decrementBalance(walletId: number, amount: string, _trx: Knex.Transaction): Promise<void> {',
  '    const wallet = this.wallets.get(walletId);',
  '    if (!wallet) {',
  '      throw new Error(`Wallet ${walletId} not found`);',
  '    }',
  '    const current = new Decimal(wallet.balance);',
  '    const sub = new Decimal(amount);',
  '    wallet.balance = current.minus(sub).toFixed(0);',
  '    wallet.updated_at = new Date();',
  '  }',
  '',
  '  public async validateBalance(walletId: number, requiredAmount: string, _trx: Knex.Transaction): Promise<boolean> {',
  '    const wallet = this.wallets.get(walletId);',
  '    if (!wallet) {',
  '      throw new Error(`Wallet ${walletId} not found`);',
  '    }',
  '    return new Decimal(wallet.balance).greaterThanOrEqualTo(new Decimal(requiredAmount));',
  '  }',
  '',
  '  public async lockAndValidateBalance(walletId: number, requiredAmount: string, _trx: Knex.Transaction): Promise<{ wallet: WalletSnapshot; isSufficient: boolean }> {',
  '    const wallet = this.wallets.get(walletId);',
  '    if (!wallet) {',
  '      throw new Error(`Wallet ${walletId} not found`);',
  '    }',
  '    return {',
  '      wallet: { ...wallet },',
  '      isSufficient: new Decimal(wallet.balance).greaterThanOrEqualTo(new Decimal(requiredAmount)),',
  '    };',
  '  }',
  '',
  '  public getBalance(walletId: number): string | null {',
  '    return this.wallets.get(walletId)?.balance ?? null;',
  '  }',
  '',
  '  public getBalanceByUserId(userId: number): string | null {',
  '    const walletId = this.userIdIndex.get(userId);',
  '    if (walletId === undefined) {',
  '      return null;',
  '    }',
  '    return this.wallets.get(walletId)?.balance ?? null;',
  '  }',
  '}',
  '',
  'class InMemoryLedgerRepository implements ILedgerRepository {',
  '  private readonly entries: Map<number, LedgerSnapshot> = new Map();',
  '  private nextId: number = 1;',
  '',
  '  constructor(initialData: LedgerSnapshot[] = []) {',
  '    for (const entry of initialData) {',
  '      this.entries.set(entry.id, { ...entry });',
  '      this.nextId = Math.max(this.nextId, entry.id + 1);',
  '    }',
  '  }',
  '',
  '  public async createEntry(params: { walletId: number; amount: string; type: LedgerEntryType; description: string }, _trx: Knex.Transaction): Promise<LedgerSnapshot> {',
  '    const entry: LedgerSnapshot = {',
  '      id: this.nextId++,',
  '      wallet_id: params.walletId,',
  '      amount: params.amount,',
  '      type: params.type,',
  '      description: params.description,',
  '      created_at: new Date(),',
  '    };',
  '    this.entries.set(entry.id, entry);',
  '    return { ...entry };',
  '  }',
  '',
  '  public async sumByWalletId(walletId: number, _trx: Knex.Transaction): Promise<string> {',
  '    let sum = new Decimal(0);',
  '    for (const entry of this.entries.values()) {',
  '      if (entry.wallet_id === walletId) {',
  '        if (entry.type === LedgerEntryType.CREDIT) {',
  '          sum = sum.plus(entry.amount);',
  '        } else {',
  '          sum = sum.minus(entry.amount);',
  '        }',
  '      }',
  '    }',
  '    return sum.toFixed(0);',
  '  }',
  '',
  '  public async findByWalletId(walletId: number, _trx: Knex.Transaction, options?: { limit?: number; offset?: number; orderBy?: SortOrder }): Promise<LedgerSnapshot[]> {',
  '    const results: LedgerSnapshot[] = [];',
  '    for (const entry of this.entries.values()) {',
  '      if (entry.wallet_id === walletId) {',
  '        results.push({ ...entry });',
  '      }',
  '    }',
  '    results.sort((a, b) => {',
  '      const cmp = a.created_at.getTime() - b.created_at.getTime();',
  '      return options?.orderBy === SortOrder.ASC ? cmp : -cmp;',
  '    });',
  '    const offset = options?.offset ?? 0;',
  '    const limit = options?.limit ?? 50;',
  '    return results.slice(offset, offset + limit);',
  '  }',
  '',
  '  public async countByWalletId(walletId: number, _trx: Knex.Transaction): Promise<number> {',
  '    let count = 0;',
  '    for (const entry of this.entries.values()) {',
  '      if (entry.wallet_id === walletId) {',
  '        count++;',
  '      }',
  '    }',
  '    return count;',
  '  }',
  '',
  '  public getEntriesByWalletId(walletId: number): LedgerSnapshot[] {',
  '    const results: LedgerSnapshot[] = [];',
  '    for (const entry of this.entries.values()) {',
  '      if (entry.wallet_id === walletId) {',
  '        results.push({ ...entry });',
  '      }',
  '    }',
  '    return results;',
  '  }',
  '}',
  '',
  "describe('WalletService - Unit Tests with Interface-Based Mocking', () => {",
  '',
  "  describe('processTransfer', () => {",
  '',
  "    it('should successfully transfer funds between two users when sender has sufficient balance', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '100000', created_at: new Date(), updated_at: new Date() },",
  "        { id: 2, user_id: 200, balance: '50000', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      const result = await walletService.processTransfer(100, 200, '10000');",
  '',
  '      expect(result.senderUserId).toBe(100);',
  '      expect(result.receiverUserId).toBe(200);',
  "      expect(result.amount).toBe('10000');",
  "      expect(result.senderNewBalance).toBe('90000');",
  "      expect(result.receiverNewBalance).toBe('60000');",
  '      expect(result.debitEntryId).toBeGreaterThan(0);',
  '      expect(result.creditEntryId).toBeGreaterThan(result.debitEntryId);',
  '',
  '      const ledgerEntries = mockLedgerRepo.getEntriesByWalletId(1);',
  '      expect(ledgerEntries).toHaveLength(1);',
  '      expect(ledgerEntries[0]!.type).toBe(LedgerEntryType.DEBIT);',
  "      expect(ledgerEntries[0]!.amount).toBe('10000');",
  '    });',
  '',
  "    it('should throw InsufficientFundsException when sender balance is insufficient', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '5000', created_at: new Date(), updated_at: new Date() },",
  "        { id: 2, user_id: 200, balance: '50000', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      await expect(walletService.processTransfer(100, 200, '10000'))",
  '        .rejects',
  '        .toBeInstanceOf(InsufficientFundsException);',
  '',
  "      await expect(walletService.processTransfer(100, 200, '10000'))",
  '        .rejects',
  "        .toThrow('Insufficient funds for this transfer');",
  '',
  '      const entries = mockLedgerRepo.getEntriesByWalletId(1);',
  '      expect(entries).toHaveLength(0);',
  '    });',
  '',
  "    it('should throw BadRequestException when senderUserId is invalid', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([]);',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      await expect(walletService.processTransfer(0, 200, '10000'))",
  '        .rejects',
  '        .toBeInstanceOf(BadRequestException);',
  '',
  "      await expect(walletService.processTransfer(-1, 200, '10000'))",
  '        .rejects',
  '        .toBeInstanceOf(BadRequestException);',
  '    });',
  '',
  "    it('should throw BadRequestException when receiverUserId is invalid', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([]);',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      await expect(walletService.processTransfer(100, 0, '10000'))",
  '        .rejects',
  '        .toBeInstanceOf(BadRequestException);',
  '',
  "      await expect(walletService.processTransfer(100, -5, '10000'))",
  '        .rejects',
  '        .toBeInstanceOf(BadRequestException);',
  '    });',
  '',
  "    it('should throw BadRequestException when attempting self-transfer', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([]);',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      await expect(walletService.processTransfer(100, 100, '10000'))",
  '        .rejects',
  '        .toBeInstanceOf(BadRequestException);',
  '',
  "      await expect(walletService.processTransfer(100, 100, '10000'))",
  '        .rejects',
  "        .toThrow('Sender and receiver cannot be the same user');",
  '    });',
  '',
  "    it('should throw BadRequestException for zero transfer amount', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([]);',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      await expect(walletService.processTransfer(100, 200, '0'))",
  '        .rejects',
  '        .toBeInstanceOf(BadRequestException);',
  '    });',
  '',
  "    it('should throw BadRequestException for negative transfer amount', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([]);',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      await expect(walletService.processTransfer(100, 200, '-5000'))",
  '        .rejects',
  '        .toBeInstanceOf(BadRequestException);',
  '    });',
  '',
  "    it('should throw BadRequestException when sender wallet does not exist', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 2, user_id: 200, balance: '50000', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      await expect(walletService.processTransfer(100, 200, '10000'))",
  '        .rejects',
  '        .toBeInstanceOf(BadRequestException);',
  '    });',
  '',
  "    it('should throw BadRequestException when receiver wallet does not exist', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '100000', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      await expect(walletService.processTransfer(100, 200, '10000'))",
  '        .rejects',
  '        .toBeInstanceOf(BadRequestException);',
  '    });',
  '',
  "    it('should handle transfers in whole kobo amounts', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '100000', created_at: new Date(), updated_at: new Date() },",
  "        { id: 2, user_id: 200, balance: '0', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      const result = await walletService.processTransfer(100, 200, '1');",
  '',
  "      expect(result.amount).toBe('1');",
  "      expect(result.senderNewBalance).toBe('99999');",
  "      expect(result.receiverNewBalance).toBe('1');",
  '    });',
  '',
  "    it('should handle very large transfer amounts without precision loss', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '100000000000', created_at: new Date(), updated_at: new Date() },",
  "        { id: 2, user_id: 200, balance: '0', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      const result = await walletService.processTransfer(100, 200, '1234567857');",
  '',
  "      expect(result.amount).toBe('1234567857');",
  "      expect(result.senderNewBalance).toBe('98765432143');",
  "      expect(result.receiverNewBalance).toBe('1234567857');",
  '    });',
  '',
  "    it('should generate unique transaction references for each transfer', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '500000', created_at: new Date(), updated_at: new Date() },",
  "        { id: 2, user_id: 200, balance: '0', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      const result1 = await walletService.processTransfer(100, 200, '1000');",
  "      const result2 = await walletService.processTransfer(100, 200, '2000');",
  "      const result3 = await walletService.processTransfer(100, 200, '3000');",
  '',
  '      expect(result1.transactionRef).not.toBe(result2.transactionRef);',
  '      expect(result2.transactionRef).not.toBe(result3.transactionRef);',
  '      expect(result3.transactionRef).not.toBe(result1.transactionRef);',
  '    });',
  '',
  "    it('should create debit and credit ledger entries with matching amounts', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '100000', created_at: new Date(), updated_at: new Date() },",
  "        { id: 2, user_id: 200, balance: '100000', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      const result = await walletService.processTransfer(100, 200, '25000');",
  '',
  '      const debitEntries = mockLedgerRepo.getEntriesByWalletId(1);',
  '      const creditEntries = mockLedgerRepo.getEntriesByWalletId(2);',
  '',
  '      expect(debitEntries).toHaveLength(1);',
  '      expect(creditEntries).toHaveLength(1);',
  '',
  '      expect(debitEntries[0]!.type).toBe(LedgerEntryType.DEBIT);',
  '      expect(creditEntries[0]!.type).toBe(LedgerEntryType.CREDIT);',
  '',
  '      expect(debitEntries[0]!.amount).toBe(creditEntries[0]!.amount);',
  "      expect(debitEntries[0]!.amount).toBe('25000');",
  '    });',
  '',
  "    it('should apply deterministic lock ordering regardless of transfer direction', async () => {",
  '      const callSequence: number[] = [];',
  '      const trackingWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '100000', created_at: new Date(), updated_at: new Date() },",
  "        { id: 2, user_id: 200, balance: '50000', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(trackingWalletRepo, mockLedgerRepo);',
  '',
  "      await walletService.processTransfer(200, 100, '10000');",
  '',
  '      const debitEntries = mockLedgerRepo.getEntriesByWalletId(2);',
  '      const creditEntries = mockLedgerRepo.getEntriesByWalletId(1);',
  '',
  '      expect(debitEntries).toHaveLength(1);',
  '      expect(creditEntries).toHaveLength(1);',
  '      expect(debitEntries[0]!.type).toBe(LedgerEntryType.DEBIT);',
  '      expect(creditEntries[0]!.type).toBe(LedgerEntryType.CREDIT);',
  '    });',
  '  });',
  '',
  "  describe('calculateAuditBalance', () => {",
  '',
  "    it('should return balanced result when ledger sum exactly matches cached balance', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '60000', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([',
  "        { id: 1, wallet_id: 1, amount: '50000', type: LedgerEntryType.CREDIT, description: 'Deposit 1', created_at: new Date() },",
  "        { id: 2, wallet_id: 1, amount: '30000', type: LedgerEntryType.CREDIT, description: 'Deposit 2', created_at: new Date() },",
  "        { id: 3, wallet_id: 1, amount: '20000', type: LedgerEntryType.DEBIT, description: 'Withdrawal', created_at: new Date() },",
  '      ]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  '      const result = await walletService.calculateAuditBalance(1);',
  '',
  '      expect(result.walletId).toBe(1);',
  "      expect(result.ledgerSum).toBe('60000');",
  "      expect(result.cachedBalance).toBe('60000');",
  '      expect(result.isBalanced).toBe(true);',
  "      expect(result.discrepancy).toBe('0');",
  '    });',
  '',
  "    it('should return balanced result when ledger sum matches cached balance with small variance', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '0', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([',
  "        { id: 1, wallet_id: 1, amount: '50000', type: LedgerEntryType.CREDIT, description: 'Deposit 1', created_at: new Date() },",
  "        { id: 2, wallet_id: 1, amount: '50000', type: LedgerEntryType.DEBIT, description: 'Withdrawal', created_at: new Date() },",
  '      ]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  '      const result = await walletService.calculateAuditBalance(1);',
  '',
  '      expect(result.isBalanced).toBe(true);',
  "      expect(result.ledgerSum).toBe('0');",
  "      expect(result.cachedBalance).toBe('0');",
  "      expect(result.discrepancy).toBe('0');",
  '    });',
  '',
  "    it('should detect discrepancy when ledger sum does not match cached balance', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '100000', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([',
  "        { id: 1, wallet_id: 1, amount: '99500', type: LedgerEntryType.CREDIT, description: 'Deposit', created_at: new Date() },",
  "        { id: 2, wallet_id: 1, amount: '500', type: LedgerEntryType.DEBIT, description: 'Withdrawal', created_at: new Date() },",
  '      ]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  '      const result = await walletService.calculateAuditBalance(1);',
  '',
  '      expect(result.isBalanced).toBe(false);',
  "      expect(result.ledgerSum).toBe('99000');",
  "      expect(result.cachedBalance).toBe('100000');",
  "      expect(result.discrepancy).toBe('1000');",
  '    });',
  '',
  "    it('should throw BadRequestException for invalid wallet ID', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([]);',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  '      await expect(walletService.calculateAuditBalance(0))',
  '        .rejects',
  '        .toBeInstanceOf(BadRequestException);',
  '',
  '      await expect(walletService.calculateAuditBalance(-1))',
  '        .rejects',
  '        .toBeInstanceOf(BadRequestException);',
  '    });',
  '',
  "    it('should throw BadRequestException when wallet not found', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([]);',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  '      await expect(walletService.calculateAuditBalance(999))',
  '        .rejects',
  '        .toBeInstanceOf(BadRequestException);',
  '    });',
  '',
  "    it('should log CRITICAL alert when balance mismatch is detected', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '100000', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([',
  "        { id: 1, wallet_id: 1, amount: '90000', type: LedgerEntryType.CREDIT, description: 'Deposit', created_at: new Date() },",
  "        { id: 2, wallet_id: 1, amount: '500', type: LedgerEntryType.DEBIT, description: 'Withdrawal', created_at: new Date() },",
  '      ]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  '      await walletService.calculateAuditBalance(1);',
  '',
  '      expect(ErrorLogger.log).toHaveBeenCalledWith(',
  '        LogLevel.FATAL,',
  "        expect.stringContaining('CRITICAL'),",
  '        expect.any(Error),',
  '        expect.objectContaining({',
  '          walletId: 1,',
  "          alertType: 'BALANCE_MISMATCH',",
  '        })',
  '      );',
  '    });',
  '',
  "    it('should handle empty ledger (wallet with only initial balance)', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '0', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  '      const result = await walletService.calculateAuditBalance(1);',
  '',
  '      expect(result.isBalanced).toBe(true);',
  "      expect(result.ledgerSum).toBe('0');",
  "      expect(result.cachedBalance).toBe('0');",
  '    });',
  '  });',
  '',
  "  describe('getWalletBalance', () => {",
  '',
  "    it('should return the wallet balance for a valid user', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '123457', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  '      const balance = await walletService.getWalletBalance(100);',
  '',
  "      expect(balance).toBe('123457');",
  '    });',
  '',
  "    it('should throw BadRequestException for invalid user ID', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([]);',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  '      await expect(walletService.getWalletBalance(0))',
  '        .rejects',
  '        .toBeInstanceOf(BadRequestException);',
  '',
  '      await expect(walletService.getWalletBalance(-1))',
  '        .rejects',
  '        .toBeInstanceOf(BadRequestException);',
  '    });',
  '',
  "    it('should throw BadRequestException when wallet not found', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([]);',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  '      await expect(walletService.getWalletBalance(999))',
  '        .rejects',
  '        .toBeInstanceOf(BadRequestException);',
  '    });',
  '  });',
  '',
  "  describe('getOrCreateWallet', () => {",
  '',
  "    it('should return existing wallet for user who already has one', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '50000', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  '      const result = await walletService.getOrCreateWallet(100);',
  '',
  '      expect(result.walletId).toBe(1);',
  "      expect(result.balance).toBe('50000');",
  '      expect(result.isNew).toBe(false);',
  '    });',
  '',
  "    it('should create new wallet if user does not have one', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([]);',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  '      const result = await walletService.getOrCreateWallet(300);',
  '',
  '      expect(result.walletId).toBeGreaterThan(0);',
  "      expect(result.balance).toBe('0');",
  '      expect(result.isNew).toBe(true);',
  '    });',
  '  });',
  '',
  "  describe('kobo integer arithmetic validation', () => {",
  '',
  "    it('should handle small kobo amount transfers without precision loss', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '100', created_at: new Date(), updated_at: new Date() },",
  "        { id: 2, user_id: 200, balance: '0', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      const result = await walletService.processTransfer(100, 200, '3');",
  '',
  "      expect(result.amount).toBe('3');",
  "      expect(result.senderNewBalance).toBe('97');",
  "      expect(result.receiverNewBalance).toBe('3');",
  '    });',
  '',
  "    it('should correctly sum and subtract with large kobo amounts', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '100000000', created_at: new Date(), updated_at: new Date() },",
  "        { id: 2, user_id: 200, balance: '0', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      const result = await walletService.processTransfer(100, 200, '12345679');",
  '',
  "      expect(result.amount).toBe('12345679');",
  "      expect(result.senderNewBalance).toBe('87654321');",
  "      expect(result.receiverNewBalance).toBe('12345679');",
  '    });',
  '  });',
  '',
  "  describe('interface contract compliance', () => {",
  '',
  "    it('should allow WalletService to be constructed with mock implementations not touching real database', () => {",
  '      const mockWalletRepo: IWalletRepository = {',
  '        findByUserIdForUpdate: jest.fn().mockResolvedValue(null),',
  '        findByUserId: jest.fn().mockResolvedValue(null),',
  '        findByWalletId: jest.fn().mockResolvedValue(null),',
  '        updateBalance: jest.fn().mockResolvedValue(undefined),',
  "        createWallet: jest.fn().mockResolvedValue({ id: 1, user_id: 1, balance: '0', created_at: new Date(), updated_at: new Date() }),",
  '        incrementBalance: jest.fn().mockResolvedValue(undefined),',
  '        decrementBalance: jest.fn().mockResolvedValue(undefined),',
  '        validateBalance: jest.fn().mockResolvedValue(true),',
  "        lockAndValidateBalance: jest.fn().mockResolvedValue({ wallet: { id: 1, user_id: 1, balance: '0', created_at: new Date(), updated_at: new Date() }, isSufficient: true }),",
  '      };',
  '',
  '      const mockLedgerRepo: ILedgerRepository = {',
  "        createEntry: jest.fn().mockResolvedValue({ id: 1, wallet_id: 1, amount: '0', type: LedgerEntryType.CREDIT, description: 'test', created_at: new Date() }),",
  "        sumByWalletId: jest.fn().mockResolvedValue('0'),",
  '        findByWalletId: jest.fn().mockResolvedValue([]),',
  '        countByWalletId: jest.fn().mockResolvedValue(0),',
  '      };',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  '      expect(walletService).toBeInstanceOf(WalletService);',
  '      expect(mockWalletRepo.findByUserId).toBeDefined();',
  '      expect(mockLedgerRepo.createEntry).toBeDefined();',
  '    });',
  '',
  "    it('should allow InMemoryLedgerRepository to fully satisfy ILedgerRepository without Knex', () => {",
  '      const ledgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const iledgerRepo: ILedgerRepository = ledgerRepo;',
  '',
  "      expect(typeof iledgerRepo.createEntry).toBe('function');",
  "      expect(typeof iledgerRepo.sumByWalletId).toBe('function');",
  "      expect(typeof iledgerRepo.findByWalletId).toBe('function');",
  "      expect(typeof iledgerRepo.countByWalletId).toBe('function');",
  '    });',
  '',
  "    it('should allow InMemoryWalletRepository to fully satisfy IWalletRepository without Knex', () => {",
  '      const walletRepo = new InMemoryWalletRepository([]);',
  '',
  '      const iwalletRepo: IWalletRepository = walletRepo;',
  '',
  "      expect(typeof iwalletRepo.findByUserIdForUpdate).toBe('function');",
  "      expect(typeof iwalletRepo.findByUserId).toBe('function');",
  "      expect(typeof iwalletRepo.findByWalletId).toBe('function');",
  "      expect(typeof iwalletRepo.incrementBalance).toBe('function');",
  "      expect(typeof iwalletRepo.decrementBalance).toBe('function');",
  "      expect(typeof iwalletRepo.createWallet).toBe('function');",
  '    });',
  '',
  "    it('should not require any network calls or Knex initialization in test suite', () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '50000', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  '      expect(() => {',
  '        walletService.getWalletBalance(100);',
  '      }).not.toThrow();',
  '    });',
  '  });',
  '',
  "  describe('processFund', () => {",
  '',
  "    it('should successfully fund a wallet and increase balance', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '50000', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      const result = await walletService.processFund(100, '20000');",
  '',
  '      expect(result.userId).toBe(100);',
  "      expect(result.amount).toBe('20000');",
  "      expect(result.newBalance).toBe('70000');",
  '      expect(result.creditEntryId).toBeGreaterThan(0);',
  '      expect(result.transactionRef).toMatch(/^FND-/);',
  '',
  '      const ledgerEntries = mockLedgerRepo.getEntriesByWalletId(1);',
  '      expect(ledgerEntries).toHaveLength(1);',
  '      expect(ledgerEntries[0]!.type).toBe(LedgerEntryType.CREDIT);',
  "      expect(ledgerEntries[0]!.amount).toBe('20000');",
  '    });',
  '',
  "    it('should handle funding with zero amount', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '50000', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      const result = await walletService.processFund(100, '0');",
  '',
  "      expect(result.newBalance).toBe('50000');",
  "      expect(result.amount).toBe('0');",
  '    });',
  '',
  "    it('should throw BadRequestException when wallet does not exist', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([]);',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      await expect(walletService.processFund(999, '10000'))",
  '        .rejects',
  '        .toBeInstanceOf(BadRequestException);',
  '    });',
  '',
  "    it('should handle multiple fundings correctly', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '0', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      await walletService.processFund(100, '10000');",
  "      await walletService.processFund(100, '20000');",
  "      const result3 = await walletService.processFund(100, '30000');",
  '',
  "      expect(result3.newBalance).toBe('60000');",
  '',
  '      const entries = mockLedgerRepo.getEntriesByWalletId(1);',
  '      expect(entries).toHaveLength(3);',
  '    });',
  '',
  "    it('should generate unique transaction references for each funding', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '0', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      const result1 = await walletService.processFund(100, '1000');",
  "      const result2 = await walletService.processFund(100, '2000');",
  '',
  '      expect(result1.transactionRef).not.toBe(result2.transactionRef);',
  '    });',
  '',
  "    it('should handle small kobo funding amounts', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '0', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      const result = await walletService.processFund(100, '1');",
  '',
  "      expect(result.newBalance).toBe('1');",
  "      expect(result.amount).toBe('1');",
  '    });',
  '  });',
  '',
  "  describe('processWithdrawal', () => {",
  '',
  "    it('should successfully withdraw from wallet and decrease balance', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '100000', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      const result = await walletService.processWithdrawal(100, '30000');",
  '',
  '      expect(result.userId).toBe(100);',
  "      expect(result.amount).toBe('30000');",
  "      expect(result.newBalance).toBe('70000');",
  '      expect(result.debitEntryId).toBeGreaterThan(0);',
  '      expect(result.transactionRef).toMatch(/^WTH-/);',
  '',
  '      const ledgerEntries = mockLedgerRepo.getEntriesByWalletId(1);',
  '      expect(ledgerEntries).toHaveLength(1);',
  '      expect(ledgerEntries[0]!.type).toBe(LedgerEntryType.DEBIT);',
  "      expect(ledgerEntries[0]!.amount).toBe('30000');",
  '    });',
  '',
  "    it('should throw InsufficientFundsException when balance is insufficient', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '5000', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      await expect(walletService.processWithdrawal(100, '10000'))",
  '        .rejects',
  '        .toBeInstanceOf(InsufficientFundsException);',
  '',
  '      const entries = mockLedgerRepo.getEntriesByWalletId(1);',
  '      expect(entries).toHaveLength(0);',
  '    });',
  '',
  "    it('should throw BadRequestException when wallet does not exist', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([]);',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      await expect(walletService.processWithdrawal(999, '10000'))",
  '        .rejects',
  '        .toBeInstanceOf(BadRequestException);',
  '    });',
  '',
  "    it('should handle complete balance withdrawal', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '50000', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      const result = await walletService.processWithdrawal(100, '50000');",
  '',
  "      expect(result.newBalance).toBe('0');",
  '    });',
  '',
  "    it('should throw InsufficientFundsException for withdrawal with zero balance', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '0', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      await expect(walletService.processWithdrawal(100, '1'))",
  '        .rejects',
  '        .toBeInstanceOf(InsufficientFundsException);',
  '    });',
  '',
  "    it('should generate unique transaction references for each withdrawal', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '100000', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      const result1 = await walletService.processWithdrawal(100, '10000');",
  "      const result2 = await walletService.processWithdrawal(100, '20000');",
  '',
  '      expect(result1.transactionRef).not.toBe(result2.transactionRef);',
  '    });',
  '',
  "    it('should handle small kobo withdrawal amounts', async () => {",
  '      const mockWalletRepo = new InMemoryWalletRepository([',
  "        { id: 1, user_id: 100, balance: '100', created_at: new Date(), updated_at: new Date() },",
  '      ]);',
  '',
  '      const mockLedgerRepo = new InMemoryLedgerRepository([]);',
  '',
  '      const walletService = new WalletService(mockWalletRepo, mockLedgerRepo);',
  '',
  "      const result = await walletService.processWithdrawal(100, '3');",
  '',
  "      expect(result.newBalance).toBe('97');",
  "      expect(result.amount).toBe('3');",
  '    });',
  '  });',
  '});'
]

fs.writeFileSync('tests/unit/wallet.service.test.ts', original.join('\n'))
console.log('Done. Written', original.length, 'lines')
