export enum LedgerEntryType {
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT',
}

export enum LogLevel {
  FATAL = 'fatal',
  ERROR = 'error',
  WARN = 'warn',
  INFO = 'info',
}

export enum CircuitBreakerState {
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
  HALF_OPEN = 'HALF_OPEN',
}

export enum HealthStatus {
  OK = 'ok',
  DEGRADED = 'degraded',
  UNHEALTHY = 'unhealthy',
}

export enum ServiceStatus {
  CONNECTED = 'connected',
  DISCONNECTED = 'disconnected',
}

export enum ServiceHealth {
  HEALTHY = 'healthy',
  UNHEALTHY = 'unhealthy',
}

export enum ResponseStatus {
  SUCCESS = 'success',
  ERROR = 'error',
}

export enum SortOrder {
  ASC = 'asc',
  DESC = 'desc',
}

export enum ValidationTarget {
  BODY = 'body',
  QUERY = 'query',
  PARAMS = 'params',
}

export enum ExceptionType {
  DOMAIN_EXCEPTION = 'DOMAIN_EXCEPTION',
  NATIVE_EXCEPTION = 'NATIVE_EXCEPTION',
}

export enum ErrorCode {
  MISSING_AUTH_TOKEN = 'MISSING_AUTH_TOKEN',
  INVALID_AUTH_TOKEN = 'INVALID_AUTH_TOKEN',
  EMAIL_REQUIRED = 'EMAIL_REQUIRED',
  BVN_REQUIRED = 'BVN_REQUIRED',
  PASSWORD_REQUIRED = 'PASSWORD_REQUIRED',
  PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT',
  FIRST_NAME_REQUIRED = 'FIRST_NAME_REQUIRED',
  LAST_NAME_REQUIRED = 'LAST_NAME_REQUIRED',
  DATE_OF_BIRTH_REQUIRED = 'DATE_OF_BIRTH_REQUIRED',
  INVALID_BVN_FORMAT = 'INVALID_BVN_FORMAT',
  USER_BLACKLISTED = 'USER_BLACKLISTED',
  REGISTRATION_FAILED = 'REGISTRATION_FAILED',
  INVALID_USER_ID = 'INVALID_USER_ID',
  USER_ID_MISSING = 'USER_ID_MISSING',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_INPUT = 'INVALID_INPUT',
  SELF_TRANSFER_NOT_ALLOWED = 'SELF_TRANSFER_NOT_ALLOWED',
  WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  SENDER_USER_ID_MISSING = 'SENDER_USER_ID_MISSING',
  BALANCE_RECONCILED = 'BALANCE_RECONCILED',
  NOT_FOUND = 'NOT_FOUND',
  BALANCE_MISMATCH = 'BALANCE_MISMATCH',
  INVALID_BVN = 'INVALID_BVN',
  INVALID_FIRST_NAME = 'INVALID_FIRST_NAME',
  INVALID_LAST_NAME = 'INVALID_LAST_NAME',
  INVALID_DATE_OF_BIRTH = 'INVALID_DATE_OF_BIRTH',
  ADJUTOR_API_ERROR = 'ADJUTOR_API_ERROR',
  ADJUTOR_NULL_RESPONSE = 'ADJUTOR_NULL_RESPONSE',
  ADJUTOR_TIMEOUT = 'ADJUTOR_TIMEOUT',
  ADJUTOR_UNREACHABLE = 'ADJUTOR_UNREACHABLE',
  ADJUTOR_REQUEST_FAILED = 'ADJUTOR_REQUEST_FAILED',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
  INVALID_JSON_PAYLOAD = 'INVALID_JSON_PAYLOAD',
  UNHANDLED_ERROR = 'UNHANDLED_ERROR',
  AMOUNT_INVALID = 'AMOUNT_INVALID',
  IDEMPOTENCY_IN_FLIGHT = 'IDEMPOTENCY_IN_FLIGHT',
}

export enum HttpStatus {
  OK = 200,
  CREATED = 201,
  NO_CONTENT = 204,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  NOT_FOUND = 404,
  CONFLICT = 409,
  INTERNAL_SERVER_ERROR = 500,
  SERVICE_UNAVAILABLE = 503,
}

export enum ReadinessStatus {
  READY = 'ready',
  NOT_READY = 'not_ready',
}
